### ISSUE TITLE
ansible-playbook 执行提交测试结果到禅道系统报错

### ISSUE THREAD

**Issue by TiashaChristabel** [easysoft/zentaoatf#11]
ansible-playbook脚本如下：
```
- hosts: ztf
  user: root
  tasks:
  - name: rm
    shell: rm -r /var/www/ztf/log/001
  - name: run
    shell: /var/www/ztf/ztf run /var/www/ztf/product3
  - name: cr
    shell: /var/www/ztf/ztf cr /var/www/ztf/log/001 -p 3 -t 10

```
结果错误："msg": "non-zero return code"
![image](https://user-images.githubusercontent.com/88478996/128320472-5d89efb5-e36d-479f-96cd-475b2b214c92.png)
